Apply kyverno

diff --git a/.github/workflows/deploy_eks_with_argocd.yaml b/.github/workflows/deploy_eks_with_argocd.yaml
--- a/.github/workflows/deploy_eks_with_argocd.yaml
+++ b/.github/workflows/deploy_eks_with_argocd.yaml
@@ -31,12 +31,12 @@ jobs:
 
     - name: Install kubectl
       run: |
-          if [[ "${{ github.event.inputs.customKyvernoPolicies }}" != "" ]]; then
-            sudo apt-get update
-            sudo apt-get install -y kubect
-          else
-           echo "No custom Kyverno Policies provided. Using default policies."
-          fi
+        if [[ -n "${{ github.event.inputs.customKyvernoPolicies }}" ]]; then
+          sudo apt-get update
+          sudo apt-get install -y kubectl
+        else
+          echo "No custom Kyverno Policies provided."
+        fi
 
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v2
@@ -195,69 +195,65 @@ jobs:
           --sync-retry-limit 5 \
           --upsert \
           --grpc-web
-
     - name: Wait for eks-${{ github.event.inputs.clusterName }}-app to become synced
       run: |
-            # Initialize time
-            TIMEOUT=660
-            INTERVAL=60
-            ELAPSED=0
+        # Initialize time
+        TIMEOUT=660
+        INTERVAL=60
+        ELAPSED=0
+        # Loop until the app becomes healthy and synced or we hit the timeout
+        while [[ $ELAPSED -lt $TIMEOUT ]]; do
+          # Get the health status and sync status of the application
+          APP_STATUS=$(argocd app get eks-${{ github.event.inputs.clusterName }}-app --output json)
+          HEALTH_STATUS=$(echo "$APP_STATUS" | jq -r '.status.health.status')
+          SYNC_STATUS=$(echo "$APP_STATUS" | jq -r '.status.sync.status')
+          echo "Application health status: $HEALTH_STATUS"
+          echo "Application sync status: $SYNC_STATUS"
 
-            # Loop until the app becomes healthy and synced or we hit the timeout
-            while [[ $ELAPSED -lt $TIMEOUT ]]; do
-              # Get the health status and sync status of the application
-              APP_STATUS=$(argocd app get eks-${{ github.event.inputs.clusterName }}-app --output json)
-              HEALTH_STATUS=$(echo "$APP_STATUS" | jq -r '.status.health.status')
-              SYNC_STATUS=$(echo "$APP_STATUS" | jq -r '.status.sync.status')
+          # If the app is both healthy and synced, break out of the loop
+          if [[ "$HEALTH_STATUS" == "Healthy" && "$SYNC_STATUS" == "Synced" ]]; then
+            echo "eks-${{ github.event.inputs.clusterName }}-app is healthy and synced. Proceeding..."
+            break
+          fi
 
-              echo "Application health status: $HEALTH_STATUS"
-              echo "Application sync status: $SYNC_STATUS"
+          # Wait for the interval duration before checking again
+          echo "Waiting for eks-${{ github.event.inputs.clusterName }}-app to become healthy and synced..."
+          sleep $INTERVAL
 
-              # If the app is both healthy and synced, break out of the loop
-              if [[ "$HEALTH_STATUS" == "Healthy" && "$SYNC_STATUS" == "Synced" ]]; then
-                echo "eks-${{ github.event.inputs.clusterName }}-app is healthy and synced. Proceeding..."
+          # Increment the elapsed time
+          ELAPSED=$((ELAPSED + INTERVAL))
+          done
+
+          # If the app is still not healthy or synced after the timeout, exit with an error
+          if [[ "$HEALTH_STATUS" != "Healthy" || "$SYNC_STATUS" != "Synced" ]]; then
+            echo "eks-${{ github.event.inputs.clusterName }}-app did not become healthy and synced within $TIMEOUT seconds. Exiting..."
+            exit 1
+          fi
+
+      - name: Check if EKS Cluster ${{ github.event.inputs.clusterName }} is Ready
+        run: |
+          # Initialize time
+          TIMEOUT=3600
+          INTERVAL=60
+          ELAPSED=0
+
+           while [[ $ELAPSED -lt $TIMEOUT ]]; do
+              STATUS=$(kubectl get cluster.eks.aws.crossplane.io ${{ github.event.inputs.clusterName }} -o jsonpath='{.status.atProvider.status}')
+              READY=$(kubectl get cluster.eks.aws.crossplane.io ${{ github.event.inputs.clusterName }} -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}')
+              echo "${{ github.event.inputs.clusterName }} status: $STATUS"
+              echo "${{ github.event.inputs.clusterName }} ready: $READY"
+
+              if [[ "$STATUS" == "ACTIVE" && "$READY" == "True" ]]; then
+                echo "EKS Cluster is created and ready."
                 break
               fi
 
               # Wait for the interval duration before checking again
-              echo "Waiting for eks-${{ github.event.inputs.clusterName }}-app to become healthy and synced..."
+              echo "Waiting for ${{ github.event.inputs.clusterName }} to become ready..."
               sleep $INTERVAL
 
               # Increment the elapsed time
               ELAPSED=$((ELAPSED + INTERVAL))
-            done
-
-            # If the app is still not healthy or synced after the timeout, exit with an error
-            if [[ "$HEALTH_STATUS" != "Healthy" || "$SYNC_STATUS" != "Synced" ]]; then
-              echo "eks-${{ github.event.inputs.clusterName }}-app did not become healthy and synced within $TIMEOUT seconds. Exiting..."
-              exit 1
-            fi
-
-      - name: Check if EKS Cluster ${{ github.event.inputs.clusterName }} is Ready
-        run: |
-              # Initialize time
-              TIMEOUT=3600
-              INTERVAL=60
-              ELAPSED=0
-
-              while [[ $ELAPSED -lt $TIMEOUT ]]; do
-                STATUS=$(kubectl get cluster.eks.aws.crossplane.io ${{ github.event.inputs.clusterName }} -o jsonpath='{.status.atProvider.status}')
-                READY=$(kubectl get cluster.eks.aws.crossplane.io ${{ github.event.inputs.clusterName }} -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}')
-
-                echo "${{ github.event.inputs.clusterName }} status: $STATUS"
-                echo "${{ github.event.inputs.clusterName }} ready: $READY"
-
-              if [[ "$STATUS" == "ACTIVE" && "$READY" == "True" ]]; then
-                  echo "EKS Cluster is created and ready."
-                  break
-                fi
-
-                # Wait for the interval duration before checking again
-                echo "Waiting for ${{ github.event.inputs.clusterName }} to become ready..."
-                sleep $INTERVAL
-
-                # Increment the elapsed time
-                ELAPSED=$((ELAPSED + INTERVAL))
               done
 
               if [[ "$STATUS" != "ACTIVE" || "$READY" != "True" ]]; then
@@ -282,13 +278,19 @@ jobs:
 
       - name: Clone Kyverno Policy Repository
         run: |
-          if [[ "${{ github.event.inputs.customKyvernoPolicies }}" != "" ]]; then
-             git clone https://github.com/nashtech-garage/kyverno.git
+          if [[ -n "${{ github.event.inputs.customKyvernoPolicies }}" ]]; then
+            rm -rf kyverno || true  # Clean previous clone
+            git clone https://github.com/nashtech-garage/kyverno.git
           fi
 
       # Apply Kyverno policies from the specific path in the repository
       - name: Apply Kyverno Policies
         run: |
-         if [[ "${{ github.event.inputs.customKyvernoPolicies }}" != "" ]]; then
-             kubectl apply -f kyverno/policies/pod-security/
-        fi
+          if [[ -n "${{ github.event.inputs.customKyvernoPolicies }}" ]]; then
+            if [ -d "kyverno/policies/pod-security/" ]; then
+              kubectl apply -f kyverno/policies/pod-security/
+            else
+              echo "Policy directory not found."
+              exit 1
+            fi
+          fi
