Apply kyverno

diff --git a/.github/workflows/deploy_eks_with_argocd.yaml b/.github/workflows/deploy_eks_with_argocd.yaml
--- a/.github/workflows/deploy_eks_with_argocd.yaml
+++ b/.github/workflows/deploy_eks_with_argocd.yaml
@@ -185,88 +185,88 @@ jobs:
             fi
     - name: Create ArgoCD app for EKS cluster
       run: |
-        argocd app create eks-${{ github.event.inputs.clusterName }}-app \
-          --repo ${{ github.event.inputs.repoURLforArgo }} \
-          --path eks-cluster \
-          --dest-server https://kubernetes.default.svc \
-          --dest-namespace aws-provider \
-          --project default \
-          --sync-policy automated \
-          --sync-retry-limit 5 \
-          --upsert \
-          --grpc-web
+          argocd app create eks-${{ github.event.inputs.clusterName }}-app \
+            --repo ${{ github.event.inputs.repoURLforArgo }} \
+            --path eks-cluster \
+            --dest-server https://kubernetes.default.svc \
+            --dest-namespace aws-provider \
+            --project default \
+            --sync-policy automated \
+            --sync-retry-limit 5 \
+            --upsert \
+            --grpc-web
 
     - name: Wait for eks-${{ github.event.inputs.clusterName }}-app to become synced
       run: |
-        # Initialize time
-        TIMEOUT=660
-        INTERVAL=60
-        ELAPSED=0
-        # Loop until the app becomes healthy and synced or we hit the timeout
-        while [[ $ELAPSED -lt $TIMEOUT ]]; do
-          # Get the health status and sync status of the application
-          APP_STATUS=$(argocd app get eks-${{ github.event.inputs.clusterName }}-app --output json)
-          HEALTH_STATUS=$(echo "$APP_STATUS" | jq -r '.status.health.status')
-          SYNC_STATUS=$(echo "$APP_STATUS" | jq -r '.status.sync.status')
-          echo "Application health status: $HEALTH_STATUS"
-          echo "Application sync status: $SYNC_STATUS"
+          # Initialize time
+          TIMEOUT=660
+          INTERVAL=60
+          ELAPSED=0
+          # Loop until the app becomes healthy and synced or we hit the timeout
+          while [[ $ELAPSED -lt $TIMEOUT ]]; do
+            # Get the health status and sync status of the application
+            APP_STATUS=$(argocd app get eks-${{ github.event.inputs.clusterName }}-app --output json)
+            HEALTH_STATUS=$(echo "$APP_STATUS" | jq -r '.status.health.status')
+            SYNC_STATUS=$(echo "$APP_STATUS" | jq -r '.status.sync.status')
+            echo "Application health status: $HEALTH_STATUS"
+            echo "Application sync status: $SYNC_STATUS"
 
-          # If the app is both healthy and synced, break out of the loop
-          if [[ "$HEALTH_STATUS" == "Healthy" && "$SYNC_STATUS" == "Synced" ]]; then
-            echo "eks-${{ github.event.inputs.clusterName }}-app is healthy and synced. Proceeding..."
-            break
-          fi
+            # If the app is both healthy and synced, break out of the loop
+            if [[ "$HEALTH_STATUS" == "Healthy" && "$SYNC_STATUS" == "Synced" ]]; then
+              echo "eks-${{ github.event.inputs.clusterName }}-app is healthy and synced. Proceeding..."
+              break
+            fi
 
-          # Wait for the interval duration before checking again
-          echo "Waiting for eks-${{ github.event.inputs.clusterName }}-app to become healthy and synced..."
-          sleep $INTERVAL
+            # Wait for the interval duration before checking again
+            echo "Waiting for eks-${{ github.event.inputs.clusterName }}-app to become healthy and synced..."
+            sleep $INTERVAL
 
-          # Increment the elapsed time
-          ELAPSED=$((ELAPSED + INTERVAL))
-          done
+            # Increment the elapsed time
+            ELAPSED=$((ELAPSED + INTERVAL))
+            done
 
-          # If the app is still not healthy or synced after the timeout, exit with an error
-          if [[ "$HEALTH_STATUS" != "Healthy" || "$SYNC_STATUS" != "Synced" ]]; then
-            echo "eks-${{ github.event.inputs.clusterName }}-app did not become healthy and synced within $TIMEOUT seconds. Exiting..."
-            exit 1
-          fi
+            # If the app is still not healthy or synced after the timeout, exit with an error
+            if [[ "$HEALTH_STATUS" != "Healthy" || "$SYNC_STATUS" != "Synced" ]]; then
+              echo "eks-${{ github.event.inputs.clusterName }}-app did not become healthy and synced within $TIMEOUT seconds. Exiting..."
+              exit 1
+            fi
 
       - name: Check if EKS Cluster ${{ github.event.inputs.clusterName }} is Ready
         run: |
-          # Initialize time
-          TIMEOUT=3600
-          INTERVAL=60
-          ELAPSED=0
+            # Initialize time
+            TIMEOUT=3600
+            INTERVAL=60
+            ELAPSED=0
 
-           while [[ $ELAPSED -lt $TIMEOUT ]]; do
-              STATUS=$(kubectl get cluster.eks.aws.crossplane.io ${{ github.event.inputs.clusterName }} -o jsonpath='{.status.atProvider.status}')
-              READY=$(kubectl get cluster.eks.aws.crossplane.io ${{ github.event.inputs.clusterName }} -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}')
-              echo "${{ github.event.inputs.clusterName }} status: $STATUS"
-              echo "${{ github.event.inputs.clusterName }} ready: $READY"
+            while [[ $ELAPSED -lt $TIMEOUT ]]; do
+                STATUS=$(kubectl get cluster.eks.aws.crossplane.io ${{ github.event.inputs.clusterName }} -o jsonpath='{.status.atProvider.status}')
+                READY=$(kubectl get cluster.eks.aws.crossplane.io ${{ github.event.inputs.clusterName }} -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}')
+                echo "${{ github.event.inputs.clusterName }} status: $STATUS"
+                echo "${{ github.event.inputs.clusterName }} ready: $READY"
 
-              if [[ "$STATUS" == "ACTIVE" && "$READY" == "True" ]]; then
-                echo "EKS Cluster is created and ready."
-                break
-              fi
+                if [[ "$STATUS" == "ACTIVE" && "$READY" == "True" ]]; then
+                  echo "EKS Cluster is created and ready."
+                  break
+                fi
 
-              # Wait for the interval duration before checking again
-              echo "Waiting for ${{ github.event.inputs.clusterName }} to become ready..."
-              sleep $INTERVAL
+                # Wait for the interval duration before checking again
+                echo "Waiting for ${{ github.event.inputs.clusterName }} to become ready..."
+                sleep $INTERVAL
 
-              # Increment the elapsed time
-              ELAPSED=$((ELAPSED + INTERVAL))
-              done
+                # Increment the elapsed time
+                ELAPSED=$((ELAPSED + INTERVAL))
+                done
 
-              if [[ "$STATUS" != "ACTIVE" || "$READY" != "True" ]]; then
-                echo "${{ github.event.inputs.clusterName }} did not become active and ready within $TIMEOUT seconds. Exiting..."
-                exit 1
-              fi
+                if [[ "$STATUS" != "ACTIVE" || "$READY" != "True" ]]; then
+                  echo "${{ github.event.inputs.clusterName }} did not become active and ready within $TIMEOUT seconds. Exiting..."
+                  exit 1
+                fi
               
       - name: Install Kyverno in the Kubernetes cluster
         run: |
-          if [[ "${{ github.event.inputs.customKyvernoPolicies }}" != "" ]]; then
-              kubectl apply -f https://raw.githubusercontent.com/kyverno/kyverno/main/config/install.yaml
-          fi
+            if [[ "${{ github.event.inputs.customKyvernoPolicies }}" != "" ]]; then
+                kubectl apply -f https://raw.githubusercontent.com/kyverno/kyverno/main/config/install.yaml
+            fi
 
       - name: Apply Kyverno policy to the cluster
         run: |
@@ -279,19 +279,19 @@ jobs:
 
       - name: Clone Kyverno Policy Repository
         run: |
-          if [[ -n "${{ github.event.inputs.customKyvernoPolicies }}" ]]; then
-            rm -rf kyverno || true  # Clean previous clone
-            git clone https://github.com/nashtech-garage/kyverno.git
-          fi
+            if [[ -n "${{ github.event.inputs.customKyvernoPolicies }}" ]]; then
+              rm -rf kyverno || true  # Clean previous clone
+              git clone https://github.com/nashtech-garage/kyverno.git
+            fi
 
       # Apply Kyverno policies from the specific path in the repository
       - name: Apply Kyverno Policies
         run: |
-          if [[ -n "${{ github.event.inputs.customKyvernoPolicies }}" ]]; then
-            if [ -d "kyverno/policies/pod-security/" ]; then
-              kubectl apply -f kyverno/policies/pod-security/
-            else
-              echo "Policy directory not found."
-              exit 1
+            if [[ -n "${{ github.event.inputs.customKyvernoPolicies }}" ]]; then
+              if [ -d "kyverno/policies/pod-security/" ]; then
+                kubectl apply -f kyverno/policies/pod-security/
+              else
+                echo "Policy directory not found."
+                exit 1
+              fi
             fi
-          fi
